config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/blog'

  get 'pages/contact'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'articles#index'
	resources :articles do
  		resources :comments
    end
    resources :tags
    resources :users

    resources :usersessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'usersessions#new'
	get 'logout' => 'usersessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    def tag_list
  		self.tags.collect do |tag|
    	tag.name
  		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
    	name
  	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper

	def index
  		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = @article.comments.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new    
	end

	def create
		@article = Article.new(article_params)
  		@article.save

  		redirect_to root_path
	end

	def edit
  		@article = Article.find(params[:id])
	end

	def update
  		@article = Article.find(params[:id])
  		@article.update(article_params)

  		flash.notice = "Article '#{@article.title}' Updated!"

  		redirect_to article_path(@article)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
  		@comment = Comment.new(comment_params)
  		@comment.article_id = params[:article_id]

  		@comment.save

  		redirect_to article_path(@comment.article)
	end

	def comment_params
	  params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end

  def contact
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
  		@tag = Tag.find(params[:id])
	end

	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :zero_users_or_authenticated, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def zero_users_or_authenticated
      unless User.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    
end

app/controllers/usersessions_controller.rb
class UsersessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
  		params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usersessions_helper.rb
module UsersessionsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>

</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id = "articles">
	<% @articles.each do |article| %>
		<li>
      		<%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
      		<%= image_tag article.image.url(:medium) %>
    	</li>
	<% end %>
</ul>
<% @articles.each do |article| %>
<div class="posts col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <div class="card">
        <div class="fakeimg" style="height:200px;"><%= image_tag article.image.url(:medium) %></div>
        	<h4><%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %></h4>
            <p><%= article.body %></p>
    </div>
</div>
<% end %>
<% if logged_in? %>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><%= image_tag @article.image.url(:medium) %></p>
<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<% if logged_in? %>
	<%= link_to "edit", edit_article_path(@article) %>

	<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
<% end %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<p>(Comment form will go here)</p>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer ================================================== -->
<div id="footer" class="margin-top-15">
  <!-- Main -->
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-6">
        <img class="footer-logo" src="#" alt="">
        <br><br>
        <p>Geo Lahore is for advertising events</p>
      </div>
      <div class="col-md-4 col-sm-6 ">
        <h4>Helpful Links</h4>
        <ul class="footer-links">
          <li><a href="#"><i class="fab fa-jedi-order"></i> Login</a></li>
          <li><a href="#">Sign Up</a></li>
          <li><a href="#">My Account</a></li>
        </ul>
        <ul class="footer-links">
          <li><a href="#">Blog</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <div class="clearfix"></div>
      </div>    
      <div class="col-md-3  col-sm-12">
        <h4>Contact Us</h4>
        <div class="text-widget">
          <span>Township Lahore</span> <br>
          Phone: <span>0334-7452064 </span><br>
          E-Mail:<span> <a href="#"><span class="__cf_email__">tajamal.azan@gmail.com</span></a> </span><br>
        </div>
        <ul class="social-icons margin-top-20">
          <li><a class="btn btn-social-icon btn-twitter"><span class="fa fa-twitter"></span></a></li>
          <li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
          <li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
          <li><a class="vimeo" href="#"><i class="icon-vimeo"></i></a></li>
          
        </ul>
      </div>
    </div>
    <!-- Copyright -->
    <div class="row">
      <div class="col-md-12">
        <div class="copyrights">© 2018 Geo Lahore. All Rights Reserved.</div>
      </div>
    </div>
  </div>
</div>
<!-- Footer / End -->
<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>
</div>
<!-- Wrapper / End -->

<script>
    $(document).ready(function() {

      var time = 7; // time in seconds

      var $progressBar,
          $bar, 
          $elem, 
          isPause, 
          tick,
          percentTime;

        //Init the carousel
        $("#owl-demo").owlCarousel({
          slideSpeed : 500,
          paginationSpeed : 500,
          singleItem : true,
          afterInit : progressBar,
          afterMove : moved,
          startDragging : pauseOnDragging
        });

        //Init progressBar where elem is $("#owl-demo")
        function progressBar(elem){
          $elem = elem;
          //build progress bar elements
          buildProgressBar();
          //start counting
          start();
        }

        //create div#progressBar and div#bar then prepend to $("#owl-demo")
        function buildProgressBar(){
          $progressBar = $("<div>",{
            id:"progressBar"
          });
          $bar = $("<div>",{
            id:"bar"
          });
          $progressBar.append($bar).prependTo($elem);
        }

        function start() {
          //reset timer
          percentTime = 0;
          isPause = false;
          //run interval every 0.01 second
          tick = setInterval(interval, 10);
        };

        function interval() {
          if(isPause === false){
            percentTime += 1 / time;
            $bar.css({
               width: percentTime+"%"
             });
            //if percentTime is equal or greater than 100
            if(percentTime >= 100){
              //slide to next item 
              $elem.trigger('owl.next')
            }
          }
        }

        //pause while dragging 
        function pauseOnDragging(){
          isPause = true;
        }

        //moved callback
        function moved(){
          //clear interval
          clearTimeout(tick);
          //start again
          start();
        }

        //uncomment this to make pause on mouseover 
        // $elem.on('mouseover',function(){
        //   isPause = true;
        // })
        // $elem.on('mouseout',function(){
        //   isPause = false;
        // })
    });
    </script>
    
    
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Basic Page Needs ================================================== -->
    <title>geolahore.com a blog on news evens and journalism - Event Tracking, government jobs, ppsc, jang news, fpsc, jobs in dubai, jobs in pakistan, pakistan jobs bank, army jobs, jobs in hyderabad, latest job jobs from home, clerk jobs, court jobs, assistant jobs, jobs in fsd, jobs district and sessions courts faisalabad jobs 2018 stenographer jobs assistant librarian jobs data entry operator jobs junior clerk jobs naib qasid jobs moazzam jobs cooks jobs. </title>
    <meta name="description" content="geo lahore in pakistan showing current events to do near me eventbrite event cinemas party and showing ipl live streaming circus in emporium" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Wrapper -->
<div id="wrapper">
<!-- Header Container ================================================== -->
<header id="header-container">
  <!-- Header -->
  <div id="header">
    <div class="container">
      <!-- Left Side Content -->
      <div class="left-side">
        <!-- Logo -->
        <div id="logo">
          <a href="index.html" title = "geolahore"><%= image_tag("logo.png", :alt => "geolahore") %></a>
        </div>
        <div class="clearfix"></div>
        <!-- Main Navigation / End -->
      </div>
      <!-- Left Side Content / End -->
      <!-- Right Side Content / End -->
      <div class="right-side">
        <!-- Mobile Navigation -->
        <div class="mmenu-trigger">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-controls="navigation">
                  <span class="hamburger-box">
              <span class="hamburger-inner"></span>
            </span>
                </button>
        </div>
        <!-- Main Navigation -->
        <nav id="navigation" class="style-1 navbar-collapse collapse">
          <ul>
            <li><a class="current" title = "geo lahore" href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact Us</a></li>
            <li>
               <% if logged_in? %>
                <%= "Logged in as #{current_user.email}" %>
                  <%= link_to "logout", logout_path %>
                <% else %>
                <%= link_to "login", login_path %>
                <% end %>
            </li>
            
          </ul>
        </nav>
      </div>
      <!-- Right Side Content / End -->
    </div>
  </div>
  <!-- Header / End -->
<div class="container-fluid">
<div class="carousel fade-carousel carousel-fade slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero container">
        <hgroup>
            <h1>Welcome to<br /> GeoLahore.com</h1> 
            <h3>A blog on news, events<br /> and journalism.</h3>
        </hgroup>
      </div>
    </div>
    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero container">        
        <hgroup>
            <h1>Welcome to<br /> GeoLahore.com</h1> 
            <h3>A blog on news, events<br /> and journalism.</h3>
        </hgroup>       
      </div>
    </div>
    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero container">        
        <hgroup>
            <h1>Welcome to<br /> GeoLahore.com</h1> 
            <h3>A blog on news, events<br /> and journalism.</h3>
        </hgroup>
      </div>
    </div>
  </div> 
</div>
</div>
<div class="clearfix"></div>
</header>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/usersessions/new.html.erb
<h1>Login</h1>
<%= form_tag usersessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>